version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RENDERTRON_HOST=http://rendertron:8080
      - MYSQL_CONN_STRING=mysql://app:app@db:3306/short_link_generator
    ports:
      - 3130:3030
    restart: always
  rendertron:
    image: tom19960222/rendertron
    cap_add:
      - SYS_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=short_link_generator
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - 13300:3306
